# filmes/management/commands/popular_filmes.py
from django.core.management.base import BaseCommand
from filmes.models import Filme

class Command(BaseCommand):
    help = 'Popula o banco de dados com filmes iniciais'

    def handle(self, *args, **kwargs):
        filmes_data = [
            # FILMES EM CARTAZ
            {
                'tmdb_id': 1,
                'titulo': 'Tron: Ares',
                'titulo_original': 'Tron: Ares',
                'sinopse': 'Ares, um sofisticado programa de IA, é enviado do mundo digital para o mundo real em uma missão perigosa, marcando o primeiro encontro da humanidade com seres de Inteligência Artificial.',
                'ano': 2025,
                'duracao': '119 min',
                'genero': 'Ficção Científica',
                'diretor': 'Joachim Rønning',
                'elenco': 'Jared Leto, Greta Lee, Evan Peters, Hasan Minhaj',
                'nota': 6.7,
                'poster': 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/3Aijwt71AG3dtI5WoYG8g9dWfQI.jpg',
                'backdrop': 'https://image.tmdb.org/t/p/original/jUplF2dluebAYdHa901mhPVOZYU.jpg',
            },
            {
                'tmdb_id': 2,
                'titulo': 'Coração de Lutador',
                'titulo_original': 'The Smashing Machine',
                'sinopse': 'A história real de Mark Kerr, bicampeão dos pesos pesados do UFC, que enfrentou batalhas pessoais intensas fora do octógono, incluindo o vício em opioides.',
                'ano': 2025,
                'duracao': '123 min',
                'genero': 'Drama',
                'diretor': 'Benny Safdie',
                'elenco': 'Dwayne Johnson, Emily Blunt, Lyndsey Gavin',
                'nota': 6.8,
                'poster': 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/270Y5jWtJMU8cK2Q8MSwJqsnUgS.jpg',
                'backdrop': 'https://image.tmdb.org/t/p/original/vfbryKoLrisx8Xh37OaTjTyrFY0.jpg',
            },
            {
                'tmdb_id': 3,
                'titulo': 'Paddington no Peru',
                'titulo_original': 'Paddington in Peru',
                'sinopse': 'Paddington e a família Brown embarcam em uma emocionante aventura na floresta amazônica do Peru em busca da lendária Cidade Perdida de Ouro.',
                'ano': 2024,
                'duracao': '106 min',
                'genero': 'Aventura',
                'diretor': 'Dougal Wilson',
                'elenco': 'Ben Whishaw, Hugh Bonneville, Emily Mortimer',
                'nota': 7.3,
                'poster': 'https://image.tmdb.org/t/p/w500/arMd4W3rqkzYfwdCgZp72BF3Tof.jpg',
                'backdrop': 'https://image.tmdb.org/t/p/original/xi1VSt3DtkevUmzCx2mNlCoDe74.jpg',
            },
            {
                'tmdb_id': 4,
                'titulo': 'Nosferatu',
                'titulo_original': 'Nosferatu',
                'sinopse': 'Uma jovem assombrada é atraída por um vampiro misterioso obcecado por ela, causando horror indescritível em seu caminho.',
                'ano': 2024,
                'duracao': '132 min',
                'genero': 'Terror',
                'diretor': 'Robert Eggers',
                'elenco': 'Bill Skarsgård, Lily-Rose Depp, Nicholas Hoult',
                'nota': 7.3,
                'poster': 'https://image.tmdb.org/t/p/w500/qD45xHA35HdJDGOaA1AgDwiWEgO.jpg',
                'backdrop': 'https://image.tmdb.org/t/p/original/18TSJF1WLA4CkymvVUcKDBwUJ9F.jpg',
            },
            
            # TOP 10
            {
                'tmdb_id': 6,
                'titulo': 'Interestelar',
                'titulo_original': 'Interstellar',
                'sinopse': 'As reservas naturais da Terra estão chegando ao fim e um grupo de astronautas recebe a missão de verificar possíveis planetas para receberem a população mundial, possibilitando a continuação da espécie.',
                'ano': 2014,
                'duracao': '169 min',
                'genero': 'Ficção Científica',
                'diretor': 'Christopher Nolan',
                'elenco': 'Matthew McConaughey, Anne Hathaway, Jessica Chastain',
                'nota': 8.7,
                'poster': 'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
                'backdrop': 'https://image.tmdb.org/t/p/original/rAiYTfKGqDCRIIqo664sY9XZIvQ.jpg',
            },
            {
                'tmdb_id': 7,
                'titulo': 'A Origem',
                'titulo_original': 'Inception',
                'sinopse': 'Dom Cobb é um ladrão com a rara habilidade de roubar segredos do inconsciente, obtidos durante o estado de sono. Impedido de retornar para sua família, ele recebe a oportunidade de se redimir ao realizar uma tarefa aparentemente impossível: plantar uma ideia na mente de alguém.',
                'ano': 2010,
                'duracao': '148 min',
                'genero': 'Ficção Científica',
                'diretor': 'Christopher Nolan',
                'elenco': 'Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen Page',
                'nota': 8.8,
                'poster': 'https://image.tmdb.org/t/p/w500/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg',
                'backdrop': 'https://image.tmdb.org/t/p/original/s3TBrRGB1iav7gFOCNx3H31MoES.jpg',
            },
            {
                'tmdb_id': 8,
                'titulo': 'O Poderoso Chefão',
                'titulo_original': 'The Godfather',
                'sinopse': 'Uma família mafiosa luta para estabelecer sua supremacia nos Estados Unidos depois da Segunda Guerra Mundial. Uma tentativa de assassinato deixa o chefão de uma família incapacitado e força os dois filhos a assumirem seus negócios.',
                'ano': 1972,
                'duracao': '175 min',
                'genero': 'Drama',
                'diretor': 'Francis Ford Coppola',
                'elenco': 'Marlon Brando, Al Pacino, James Caan',
                'nota': 9.2,
                'poster': 'https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
                'backdrop': 'https://image.tmdb.org/t/p/original/tmU7GeKVybMWFButWEGl2M4GeiP.jpg',
            },
            {
                'tmdb_id': 9,
                'titulo': 'Pulp Fiction',
                'titulo_original': 'Pulp Fiction',
                'sinopse': 'Assassino que trabalha para a máfia se apaixona pela esposa de seu chefe quando é escalado para acompanhá-la, um boxeador descumpre sua promessa de perder uma luta e um casal tenta um assalto que rapidamente sai do controle.',
                'ano': 1994,
                'duracao': '154 min',
                'genero': 'Crime',
                'diretor': 'Quentin Tarantino',
                'elenco': 'John Travolta, Uma Thurman, Samuel L. Jackson',
                'nota': 8.9,
                'poster': 'https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg',
                'backdrop': 'https://image.tmdb.org/t/p/original/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg',
            },
            {
                'tmdb_id': 10,
                'titulo': 'Matrix',
                'titulo_original': 'The Matrix',
                'sinopse': 'Um hacker descobre que a realidade em que vive é uma simulação criada por máquinas, e se junta a outros revolucionários para combatê-las.',
                'ano': 1999,
                'duracao': '136 min',
                'genero': 'Ficção Científica',
                'diretor': 'Lana Wachowski, Lilly Wachowski',
                'elenco': 'Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss',
                'nota': 8.7,
                'poster': 'https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg',
                'backdrop': 'https://image.tmdb.org/t/p/original/icmmSD4vTTDKOq2vvdulafOGw93.jpg',
            },
            {
                'tmdb_id': 11,
                'titulo': 'Clube da Luta',
                'titulo_original': 'Fight Club',
                'sinopse': 'Um homem deprimido que sofre de insônia conhece um estranho vendedor chamado Tyler Durden e se vê vivendo em uma casa suja depois que seu perfeito apartamento é destruído. A dupla forma um clube com regras rígidas onde homens lutam.',
                'ano': 1999,
                'duracao': '139 min',
                'genero': 'Drama',
                'diretor': 'David Fincher',
                'elenco': 'Brad Pitt, Edward Norton, Helena Bonham Carter',
                'nota': 8.8,
                'poster': 'https://image.tmdb.org/t/p/w500/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg',
                'backdrop': 'https://image.tmdb.org/t/p/original/hZkgoQYus5vegHoetLkCJzb17zJ.jpg',
            },
            {
                'tmdb_id': 12,
                'titulo': 'Forrest Gump',
                'titulo_original': 'Forrest Gump',
                'sinopse': 'Quarenta anos da história dos Estados Unidos, vistos pelos olhos de Forrest Gump, um rapaz com QI abaixo da média que consegue participar de momentos importantes da história americana.',
                'ano': 1994,
                'duracao': '142 min',
                'genero': 'Drama',
                'diretor': 'Robert Zemeckis',
                'elenco': 'Tom Hanks, Robin Wright, Gary Sinise',
                'nota': 8.8,
                'poster': 'https://image.tmdb.org/t/p/w500/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg',
                'backdrop': 'https://image.tmdb.org/t/p/original/7c9UVPPiTPltouxRVY6N9uUaHNJ.jpg',
            },
            {
                'tmdb_id': 13,
                'titulo': 'O Senhor dos Anéis',
                'titulo_original': 'The Lord of the Rings: The Return of the King',
                'sinopse': 'Sauron planeja um grande ataque a Minas Tirith, capital de Gondor, o que faz com que Gandalf e Pippin partam para o local na intenção de ajudar a resistência.',
                'ano': 2003,
                'duracao': '201 min',
                'genero': 'Aventura',
                'diretor': 'Peter Jackson',
                'elenco': 'Elijah Wood, Viggo Mortensen, Ian McKellen',
                'nota': 8.9,
                'poster': 'https://image.tmdb.org/t/p/w500/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg',
                'backdrop': 'https://image.tmdb.org/t/p/original/2u7zbn8EudG6kLlBzUYqP8RyFU4.jpg',
            },
            {
                'tmdb_id': 14,
                'titulo': 'Coringa',
                'titulo_original': 'Joker',
                'sinopse': 'Arthur Fleck trabalha como palhaço para uma agência de talentos e, toda semana, precisa comparecer a uma agente social, devido aos seus conhecidos problemas mentais. Após ser demitido, Fleck reage e os eventos acabam o levando ao caminho para se tornar o Coringa.',
                'ano': 2019,
                'duracao': '122 min',
                'genero': 'Crime',
                'diretor': 'Todd Phillips',
                'elenco': 'Joaquin Phoenix, Robert De Niro, Zazie Beetz',
                'nota': 8.4,
                'poster': 'https://image.tmdb.org/t/p/w500/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg',
                'backdrop': 'https://image.tmdb.org/t/p/original/n6bUvigpRFqSwmPp1m2YADdbRBc.jpg',
            },
            
            # INDICAÇÕES
            {
                'tmdb_id': 15,
                'titulo': 'Cidade de Deus',
                'titulo_original': 'Cidade de Deus',
                'sinopse': 'Buscapé é um jovem pobre, negro e sensível, que cresce em um universo de muita violência. Ele vive na Cidade de Deus, favela carioca conhecida por ser um dos locais mais violentos do Rio.',
                'ano': 2002,
                'duracao': '130 min',
                'genero': 'Drama',
                'diretor': 'Fernando Meirelles, Kátia Lund',
                'elenco': 'Alexandre Rodrigues, Leandro Firmino, Phellipe Haagensen',
                'nota': 8.6,
                'poster': 'https://upload.wikimedia.org/wikipedia/pt/1/10/CidadedeDeus.jpg',
                'backdrop': 'https://image.tmdb.org/t/p/original/k7eYdGvlErt8L8PPWYfHSqQ5e3Y.jpg',
            },
            {
                'tmdb_id': 16,
                'titulo': 'Toy Story',
                'titulo_original': 'Toy Story',
                'sinopse': 'Quando o menino Andy ganha um boneco do patrulheiro espacial Buzz Lightyear, o caubói Woody, que até então era o brinquedo favorito, fica com ciúmes. Quando Buzz e Woody se perdem, precisam superar as diferenças.',
                'ano': 1995,
                'duracao': '81 min',
                'genero': 'Animação',
                'diretor': 'John Lasseter',
                'elenco': 'Tom Hanks, Tim Allen, Don Rickles',
                'nota': 8.3,
                'poster': 'https://image.tmdb.org/t/p/w500/uXDfjJbdP4ijW5hWSBrPrlKpxab.jpg',
                'backdrop': 'https://image.tmdb.org/t/p/original/8lWYRLE6ahFdzpWjSNDT5kVsSyL.jpg',
            },
            {
                'tmdb_id': 17,
                'titulo': 'Gladiador',
                'titulo_original': 'Gladiator',
                'sinopse': 'Maximus é um general romano que é forçado a se tornar gladiador após seu imperador ser assassinado.',
                'ano': 2000,
                'duracao': '155 min',
                'genero': 'Ação',
                'diretor': 'Ridley Scott',
                'elenco': 'Russell Crowe, Joaquin Phoenix, Connie Nielsen',
                'nota': 8.5,
                'poster': 'https://image.tmdb.org/t/p/w500/ty8TGRuvJLPUmAR1H1nRIsgwvim.jpg',
                'backdrop': 'https://image.tmdb.org/t/p/original/tuf1nRLWfHqFYwdQhGnqFVCfpwj.jpg',
            },
            {
                'tmdb_id': 18,
                'titulo': 'De Volta para o Futuro',
                'titulo_original': 'Back to the Future',
                'sinopse': 'Marty McFly, um adolescente, é enviado acidentalmente de volta no tempo, de 1985 para 1955, em um DeLorean que viaja no tempo.',
                'ano': 1985,
                'duracao': '116 min',
                'genero': 'Aventura',
                'diretor': 'Robert Zemeckis',
                'elenco': 'Michael J. Fox, Christopher Lloyd, Lea Thompson',
                'nota': 8.5,
                'poster': 'https://image.tmdb.org/t/p/w500/fNOH9f1aA7XRTzl1sAOx9iF553Q.jpg',
                'backdrop': 'https://image.tmdb.org/t/p/original/nKKOxROMC1h4v1j5ppq6sDuzqr2.jpg',
            },
            {
                'tmdb_id': 19,
                'titulo': 'O Iluminado',
                'titulo_original': 'The Shining',
                'sinopse': 'Jack Torrance aceita um emprego como zelador de inverno em um hotel isolado nas montanhas do Colorado.',
                'ano': 1980,
                'duracao': '144 min',
                'genero': 'Terror',
                'diretor': 'Stanley Kubrick',
                'elenco': 'Jack Nicholson, Shelley Duvall, Danny Lloyd',
                'nota': 8.4,
                'poster': 'https://image.tmdb.org/t/p/w500/xazWoLealQwEgqZ89MLZklLZD3k.jpg',
                'backdrop': 'https://image.tmdb.org/t/p/original/nWCb0LhzAhMIF3qBEK7wmJzLEFp.jpg',
            },
            {
                'tmdb_id': 20,
                'titulo': 'La La Land',
                'titulo_original': 'La La Land',
                'sinopse': 'Mia é uma atriz iniciante que serve cafés aos astros de cinema enquanto tenta entrar em algum teste. Sebastian é um pianista que se apresenta em bares ordinários.',
                'ano': 2016,
                'duracao': '128 min',
                'genero': 'Romance',
                'diretor': 'Damien Chazelle',
                'elenco': 'Ryan Gosling, Emma Stone, Rosemarie DeWitt',
                'nota': 8.0,
                'poster': 'https://image.tmdb.org/t/p/w500/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg',
                'backdrop': 'https://image.tmdb.org/t/p/original/fp6X2WVwOe4SyxU2RozxDcJlAAB.jpg',
            },
            
            # EM ALTA
            {
                'tmdb_id': 21,
                'titulo': 'Vingadores: Ultimato',
                'titulo_original': 'Avengers: Endgame',
                'sinopse': 'Após Thanos eliminar metade das criaturas vivas, os Vingadores têm de lidar com a perda de amigos e entes queridos. Com Tony Stark vagando perdido no espaço sem água e comida, Steve Rogers e Natasha Romanov lideram a resistência contra o titã louco.',
                'ano': 2019,
                'duracao': '181 min',
                'genero': 'Ação',
                'diretor': 'Anthony Russo, Joe Russo',
                'elenco': 'Robert Downey Jr., Chris Evans, Mark Ruffalo',
                'nota': 8.4,
                'poster': 'https://image.tmdb.org/t/p/w500/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg',
                'backdrop': 'https://image.tmdb.org/t/p/original/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg',
            },
            {
                'tmdb_id': 22,
                'titulo': 'Se Beber, Não Case!',
                'titulo_original': 'The Hangover',
                'sinopse': 'Três amigos vão a Las Vegas para comemorar a despedida de solteiro de Doug. No dia seguinte, acordam de ressaca sem se lembrar de nada e sem o noivo.',
                'ano': 2009,
                'duracao': '100 min',
                'genero': 'Comédia',
                'diretor': 'Todd Phillips',
                'elenco': 'Bradley Cooper, Ed Helms, Zach Galifianakis',
                'nota': 7.7,
                'poster': 'https://m.media-amazon.com/images/I/618FiO7H+sS._AC_SY741_.jpg',
                'backdrop': 'https://image.tmdb.org/t/p/original/qH3RwqNFnPkOOaR9WpS8zOp5i8u.jpg',
            },
            {
                'tmdb_id': 23,
                'titulo': 'Avatar',
                'titulo_original': 'Avatar',
                'sinopse': 'Jake Sully, um ex-fuzileiro naval paraplégico, é enviado ao planeta Pandora, onde aprende os modos de vida dos nativos Na\'vi e deve decidir onde estão suas verdadeiras lealdades.',
                'ano': 2009,
                'duracao': '162 min',
                'genero': 'Ficção Científica',
                'diretor': 'James Cameron',
                'elenco': 'Sam Worthington, Zoe Saldana, Sigourney Weaver',
                'nota': 7.9,
                'poster': 'https://upload.wikimedia.org/wikipedia/pt/thumb/b/b0/Avatar-Teaser-Poster.jpg/250px-Avatar-Teaser-Poster.jpg',
                'backdrop': 'https://image.tmdb.org/t/p/original/o0s4XsEDfDlvit5pDRKjzXR4pp2.jpg',
            },
            {
                'tmdb_id': 24,
                'titulo': 'O Cavaleiro das Trevas',
                'titulo_original': 'The Dark Knight',
                'sinopse': 'Batman tem um grande aliado no combate ao crime, o tenente James Gordon, e o promotor público Harvey Dent. Entretanto, os três serão surpreendidos por uma mente criminosa conhecida como Coringa.',
                'ano': 2008,
                'duracao': '152 min',
                'genero': 'Ação',
                'diretor': 'Christopher Nolan',
                'elenco': 'Christian Bale, Heath Ledger, Aaron Eckhart',
                'nota': 9.0,
                'poster': 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
                'backdrop': 'https://image.tmdb.org/t/p/original/hqkIcbrOHL86UncnHIsHVcVmzue.jpg',
            },
            {
                'tmdb_id': 25,
                'titulo': 'Shrek',
                'titulo_original': 'Shrek',
                'sinopse': 'Um ogro solitário vê seu pântano ser invadido por uma multidão de personagens de contos de fadas banidos pelo maldoso Lorde Farquaad.',
                'ano': 2001,
                'duracao': '90 min',
                'genero': 'Animação',
                'diretor': 'Andrew Adamson, Vicky Jenson',
                'elenco': 'Mike Myers, Eddie Murphy, Cameron Diaz',
                'nota': 7.9,
                'poster': 'https://image.tmdb.org/t/p/w500/iB64vpL3dIObOtMZgX3RqdVdQDc.jpg',
                'backdrop': 'https://image.tmdb.org/t/p/original/dEkaN8NKxm4eXVIXdJKMCfwYL3g.jpg',
            },
            {
                'tmdb_id': 26,
                'titulo': 'Titanic',
                'titulo_original': 'Titanic',
                'sinopse': 'Jack Dawson e Rose DeWitt Bukater, membros de classes sociais distintas, se apaixonam a bordo do RMS Titanic durante sua fatídica viagem inaugural.',
                'ano': 1997,
                'duracao': '194 min',
                'genero': 'Romance',
                'diretor': 'James Cameron',
                'elenco': 'Leonardo DiCaprio, Kate Winslet, Billy Zane',
                'nota': 7.9,
                'poster': 'https://image.tmdb.org/t/p/w500/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg',
                'backdrop': 'https://image.tmdb.org/t/p/original/tHXvBxIoqUxqg7K5W8l9nMOFI76.jpg',
            },
        ]

        total_criados = 0
        total_atualizados = 0
        
        for filme_data in filmes_data:
            filme, criado = Filme.objects.update_or_create(
                tmdb_id=filme_data['tmdb_id'],
                defaults=filme_data
            )
            
            if criado:
                total_criados += 1
                self.stdout.write(self.style.SUCCESS(f'✅ Criado: {filme.titulo}'))
            else:
                total_atualizados += 1
                self.stdout.write(self.style.WARNING(f'🔄 Atualizado: {filme.titulo}'))
        
        self.stdout.write(self.style.SUCCESS(f'\n🎬 CONCLUÍDO!'))
        self.stdout.write(self.style.SUCCESS(f'📊 {total_criados} filmes criados'))
        self.stdout.write(self.style.SUCCESS(f'🔄 {total_atualizados} filmes atualizados'))
        self.stdout.write(self.style.SUCCESS(f'📁 Total: {total_criados + total_atualizados} filmes no banco'))