# Generated by Django 5.2.6 on 2025-10-21 20:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('titulo_original', models.CharField(blank=True, max_length=200)),
                ('ano', models.IntegerField()),
                ('genero', models.CharField(choices=[('acao', 'Ação'), ('aventura', 'Aventura'), ('comedia', 'Comédia'), ('drama', 'Drama'), ('ficcao_cientifica', 'Ficção Científica'), ('terror', 'Terror'), ('romance', 'Romance'), ('suspense', 'Suspense')], max_length=50)),
                ('duracao', models.CharField(max_length=20)),
                ('sinopse', models.TextField()),
                ('diretor', models.CharField(max_length=200)),
                ('elenco', models.TextField(blank=True)),
                ('poster_url', models.URLField(max_length=500)),
                ('nota_imdb', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('data_adicao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Filme',
                'verbose_name_plural': 'Filmes',
                'ordering': ['-ano', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='FilmeUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('assistido', 'Assistido'), ('assistindo', 'Assistindo'), ('quero_assistir', 'Quero Assistir')], default='quero_assistir', max_length=20)),
                ('nota', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.TextField(blank=True)),
                ('data_adicao', models.DateTimeField(auto_now_add=True)),
                ('data_assistido', models.DateField(blank=True, null=True)),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='filmes.filme')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filmes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Filme do Usuário',
                'verbose_name_plural': 'Filmes dos Usuários',
                'ordering': ['-data_adicao'],
                'unique_together': {('usuario', 'filme')},
            },
        ),
    ]
