# Generated by Django 5.2.6 on 2025-10-22 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='filme',
            old_name='data_adicao',
            new_name='data_criacao',
        ),
        migrations.RenameField(
            model_name='filme',
            old_name='poster_url',
            new_name='poster',
        ),
        migrations.RemoveField(
            model_name='filme',
            name='nota_imdb',
        ),
        migrations.AddField(
            model_name='filme',
            name='backdrop',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='filme',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='filme',
            name='nota',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='filme',
            name='tmdb_id',
            field=models.IntegerField(blank=True, help_text='ID do filme no TMDB', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='filme',
            name='diretor',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='filme',
            name='duracao',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='filme',
            name='elenco',
            field=models.TextField(blank=True, help_text='Elenco principal separado por vírgulas'),
        ),
        migrations.AlterField(
            model_name='filme',
            name='genero',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='filme',
            name='sinopse',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='filme',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='filme',
            name='titulo_original',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('editado', models.BooleanField(default=False)),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='filmes.filme')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comentário',
                'verbose_name_plural': 'Comentários',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Estante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('assistido', 'Assistido'), ('quero_assistir', 'Quero Assistir'), ('assistindo', 'Assistindo')], default='quero_assistir', max_length=20)),
                ('nota_pessoal', models.DecimalField(blank=True, decimal_places=1, help_text='Nota de 0 a 10', max_digits=3, null=True)),
                ('data_adicionado', models.DateTimeField(auto_now_add=True)),
                ('data_assistido', models.DateField(blank=True, null=True)),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='em_estantes', to='filmes.filme')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estante', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Item da Estante',
                'verbose_name_plural': 'Itens da Estante',
                'ordering': ['-data_adicionado'],
                'unique_together': {('usuario', 'filme')},
            },
        ),
        migrations.CreateModel(
            name='Reacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('curtida', '❤️ Curtida')], default='curtida', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reacoes', to='filmes.comentario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reação',
                'verbose_name_plural': 'Reações',
                'ordering': ['-data_criacao'],
                'unique_together': {('comentario', 'usuario')},
            },
        ),
        migrations.DeleteModel(
            name='FilmeUsuario',
        ),
    ]
