name: Build and deploy Python app to Azure Web App

on:
  push:
    branches:
      - producao
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      # ESTA É A MUDANÇA PRINCIPAL
      - name: Install dependencies into a local folder
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt --target=".python_packages/lib/site-packages"
          deactivate

      - name: Cleaning testing files
        run: |
          rm -f db.sqlite3
          rm -f .env

      # Vamos zipar o código E os pacotes instalados
      - name: Zip artifact for deployment
        run: zip release.zip . -r -x "venv/*" -x ".git/*" -x "__pycache__/*" -x ".vscode/*"

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
      
      # O deploy continua o mesmo, mas agora envia o "pacote completo"
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'cineestante-app'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: release.zip

