name: Build and deploy Python app to Azure Web App

on:
  push:
    branches:
      - producao
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      # Limpa arquivos de teste/locais
      - name: Cleaning testing files
        run: |
          rm -f db.sqlite3
          rm -f .env
      
      # Apenas compacta o código-fonte, excluindo o venv, .git, etc.
      - name: Zip artifact for deployment
        run: zip release.zip . -r -x "venv/*" -x ".git/*" -x "__pycache__/*"

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip # Sobe apenas o arquivo zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
      
      # Esta é a ação de deploy limpa.
      # Ela apenas envia o 'release.zip'.
      # A Azure vai detectar o 'requirements.txt' dentro do zip e instalar tudo sozinha.
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'cineestante-app'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: release.zip 
          # TODOS os comandos 'scm-do-build-during-deployment' e 'post-build-command'
          # foram removidos porque estavam errados.

