<<<<<<< HEAD
name: Build and deploy Python app to Azure Web App
=======
name: Build and deploy Python app to Azure Web App - cineestante-app
>>>>>>> f63da5e2837914c7e6a30ad8c3216896b72ebdaf

on:
  push:
    branches:
      - producao
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
<<<<<<< HEAD
        run: pip install -r requirements.txt
        
      - name: Cleaning testing files
        run: |
          rm -f db.sqlite3
          rm -f .env
      
      - name: Zip artifact for deployment
        run: zip release.zip ./* -r
=======
        run: pip install -r project/requirements.txt
        
      - name: Cleaning testing files
        run: |
          cd project/
          rm -f db.sqlite3
          rm -f .env
          cd ..
      
      - name: Zip artifact for deployment
        run: |
          cd project/
          zip release.zip ./* -r
          cd ..
          mv project/release.zip .
>>>>>>> f63da5e2837914c7e6a30ad8c3216896b72ebdaf

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'cineestante-app'
          slot-name: 'Production'
<<<<<<< HEAD
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
=======
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_XXXXXXXX }}
>>>>>>> f63da5e2837914c7e6a30ad8c3216896b72ebdaf
